version: '3.5'
services:
 adminer:  #Optional for accessing databases
  image: adminer
  restart: always
  container_name: adminer
  ports:
   - 8080:8080
  networks:
   zbx_net_backend:
#    aliases:
#     - mysql-server
#     - zabbix-database
#     - mysql-database 
#     - adminer
   zbx_net_frontend:
    ipv4_address: '172.30.238.70'