version: '2'

services:
  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
 # network_mode: host 
    networks:
      zbx_net_frontend:
        ipv4_address: '172.30.238.70'
#networks:
#  zbx_net_frontend:
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
#    ipam:
#      driver: default
#      config:
#       - subnet: 172.30.238.0/24	
